apiVersion: v1
kind: Pod

metadata:
  name: crash-app

spec:
  containers:
    - name: crash-container
      image: busybox

      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Application failed to start"
          sleep 5
          exit 1