function AiOllamaPanel({ model, latency, duration, source }) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900/95 p-6 shadow-sm ring-1 ring-cyan-400/10">
      <div className="mb-4 flex items-center justify-between gap-3">
        <div>
          <p className="text-sm uppercase tracking-[0.22em] text-slate-400">Generated by</p>
          <h3 className="mt-2 text-2xl font-semibold text-white">Ollama AI Engine</h3>
        </div>
        <div className="rounded-full bg-cyan-500/10 px-4 py-2 text-xs uppercase tracking-[0.24em] text-cyan-300 ring-1 ring-cyan-500/20">
          Enterprise AI
        </div>
      </div>

      <div className="space-y-3 text-sm text-slate-300">
        <div className="flex items-center justify-between gap-4 rounded-2xl bg-[#020617] px-4 py-3">
          <span>Model</span>
          <span className="font-semibold text-white">{model}</span>
        </div>
        <div className="flex items-center justify-between gap-4 rounded-2xl bg-[#020617] px-4 py-3">
          <span>AI latency</span>
          <span className="font-semibold text-white">{latency} ms</span>
        </div>
        <div className="flex items-center justify-between gap-4 rounded-2xl bg-[#020617] px-4 py-3">
          <span>Analysis duration</span>
          <span className="font-semibold text-white">{duration}s</span>
        </div>
        <div className="flex items-center justify-between gap-4 rounded-2xl bg-[#020617] px-4 py-3">
          <span>Telemetry source</span>
          <span className="font-semibold text-white">{source}</span>
        </div>
      </div>
    </div>
  )
}

export default AiOllamaPanel
